export const checkBoxValue = ['Name', 'SKU', 'Full Description'];
export const optionItemPerPage = [10, 25, 50, 75, 100];

interface TabelHeader {
  name: string;
  canSort: boolean;
}

export interface Memberships {
  label: string;
  value: number | string | null;
}

interface OG_tag {
  type: string;
  label: string;
}

export const tableHeaderLabel: TabelHeader[] = [
  {
    name: 'SKU',
    canSort: true,
  },
  {
    name: 'Name',
    canSort: true,
  },
  {
    name: 'Category',
    canSort: false,
  },
  {
    name: 'Price',
    canSort: false,
  },
  {
    name: 'In stock',
    canSort: false,
  },
  {
    name: 'Vendor',
    canSort: false,
  },
  {
    name: 'Arrival Date',
    canSort: false,
  },
];
export const sale_unit = ['$', '%'];

export const memberships: Memberships[] = [
  {
    label: 'General ',
    value: 4,
  },
];

export const ogTags: OG_tag[] = [
  {
    type: '0',
    label: 'Autogenerated',
  },
  {
    type: '1',
    label: 'Custom',
  },
];

export const metaDesc: OG_tag[] = [
  {
    type: 'A',
    label: 'Autogenerated',
  },
  {
    type: 'C',
    label: 'Custom',
  },
];

const ITEM_HEIGHT = 48;
const ITEM_PADDING_BOTTOM = -30;
export const MenuProps = {
  PaperProps: {
    style: {
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_BOTTOM,
      width: 250,
    },
  },
};
